name: Quick KB
description: A Knowledge Base application built with Laravel and SQLite.
keywords:
  - php
  - laravel
  - sqlite
  - nginx
website: https://github.com/cs-quicklabs/quick-kb
repository: https://github.com/cs-quicklabs/quick-kb
stack: container
dockerfile_path: Dockerfile
dockerfile_context: .
dockerfile_context_path: .
features:
  runtime-env-vars: true
env:
  - key: APP_ENV
    value: production
  - key: APP_KEY
    generateValue: true
  - key: DB_CONNECTION
    value: sqlite
  - key: DB_DATABASE
    value: database/database.sqlite
  - key: SCOUT_DRIVER
    value: tntsearch
  - key: PORT
    value: "80"
  - key: SESSION_DRIVER
    value: database
  - key: SESSION_DOMAIN
    value: null
  - key: SESSION_SECURE_COOKIE
    value: "true" 